services:
  postgres:
    image: postgres:16-alpine
    container_name: accounting-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-accounting_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - accounting-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  accounting-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accounting-system
    ports:
      # Формат: "внешний_порт:внутренний_порт"
      # Приложение доступно на порту 8880
      - "8880:8880"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-accounting_db}
    networks:
      - accounting-network

volumes:
  postgres_data:


networks:
  accounting-network:
    driver: bridge
